services:
  - type: web
    name: metrapp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn metrapp_backend.wsgi
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: clave-super-secreta
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: metrapp-db
          property: connectionString
databases:
  - name: metrapp-db
    plan: free
