# Generated by Django 5.2.3 on 2025-07-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True)),
                ('nombre_tecnico', models.CharField(max_length=100)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('clasificacion_metrologica', models.CharField(choices=[('PN', 'Patrón Nacional'), ('PR', 'Patrón de Referencia'), ('PT', 'Patrón de Trabajo'), ('EA', 'Equipo Auxiliar')], max_length=2)),
                ('laboratorio_responsable', models.CharField(choices=[('LPR', 'LPR'), ('LFU', 'LFU'), ('LLO', 'LLO'), ('LMA', 'LMA'), ('LCB', 'LCB'), ('LVD', 'LVD'), ('LTE', 'LTE'), ('LEL', 'LEL'), ('LTF', 'LTF'), ('LMQ', 'LMQ')], max_length=4)),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Formato: Largo x Ancho x Alto', max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('llamado_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fuente_financiacion', models.CharField(blank=True, choices=[('TESORO', 'Tesoro'), ('PROYECTO', 'Proyecto Internacional'), ('COOPERACION', 'Cooperación'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('fuente_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('garantia_vigente', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('fecha_vencimiento_garantia', models.DateField(blank=True, null=True)),
                ('fecha_calibracion_inicial', models.DateField(blank=True, null=True)),
                ('ultima_fecha_calibracion', models.DateField(blank=True, null=True)),
                ('calibrado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_certificado_calibracion', models.CharField(blank=True, max_length=255, null=True)),
                ('patron_asociado', models.CharField(blank=True, max_length=255, null=True)),
                ('intervalo_calibracion', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_verificacion', models.PositiveIntegerField(blank=True, help_text='Frecuencia en meses', null=True)),
                ('parametro_verificado', models.CharField(blank=True, max_length=255, null=True)),
                ('tolerancia_permitida', models.CharField(blank=True, max_length=255, null=True)),
                ('criterio_aceptacion', models.CharField(blank=True, max_length=500, null=True)),
                ('observaciones_verificacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDeriva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_deriva', models.DecimalField(decimal_places=5, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_instrumentos.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoCalibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calibracion', models.DateField()),
                ('fecha_proxima_calibracion', models.DateField()),
                ('resultado', models.TextField()),
                ('incertidumbre', models.DecimalField(decimal_places=5, max_digits=10)),
                ('archivo_pdf', models.FileField(upload_to='certificados/')),
                ('tecnico', models.CharField(max_length=100)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='gestion_instrumentos.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_certificados', to='gestion_instrumentos.instrumento')),
            ],
        ),
    ]
