# Generated by Django 5.2.3 on 2025-06-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='costo_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
