# Generated by Django 5.2.3 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_instrumentos', '0002_alter_instrumento_costo_adquisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='criterio_aceptacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='intervalo_verificacion',
            field=models.PositiveIntegerField(blank=True, help_text='Frecuencia en meses', null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='observaciones_verificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='parametro_verificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tolerancia_permitida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
